// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrcoimrfkskuqimgaiww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yY29pbXJma3NrdXFpbWdhaXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwODQ5MTAsImV4cCI6MjA1NDY2MDkxMH0.xc3t1duk6m7aJsuLGnCPtzmuoFcoTf4IW4cUV0oN_kU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);